<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Admin_inline-flex rounded-full px-2 te_e1ca0c</name>
   <tag></tag>
   <elementGuidId>21a25175-9323-4c2d-89c9-77e4561aff13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.inline-flex.rounded-full.px-2.text-xs.leading-5.font-semibold.bg-green-100.text-green-800</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/main/div/div[2]/div[2]/div[2]/div/table/tbody/tr/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Active&quot;i >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ee15369-3274-4a78-a70e-94e9ec8fc609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex rounded-full px-2 text-xs leading-5 font-semibold bg-green-100 text-green-800</value>
      <webElementGuid>ffe25e97-7de8-4efa-82dd-7b857ff30dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>9bdeba68-f93c-402d-8086-00a916a59cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/main[@class=&quot;h-[calc(100vh-4rem)] overflow-y-auto bg-gray-50 pb-20&quot;]/div[@class=&quot;container mx-auto px-4 py-6 sm:py-8&quot;]/div[@class=&quot;mb-6&quot;]/div[@class=&quot;hidden md:block&quot;]/div[@class=&quot;rounded-md border&quot;]/div[@class=&quot;relative w-full overflow-x-auto&quot;]/table[@class=&quot;w-full caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0&quot;]/tr[@class=&quot;data-[state=selected]:bg-muted border-b transition-colors hover:bg-gray-50&quot;]/td[@class=&quot;p-2 align-middle whitespace-nowrap [&amp;:has([role=checkbox])]:pr-0 [&amp;>[role=checkbox]]:translate-y-[2px] py-4&quot;]/span[@class=&quot;inline-flex rounded-full px-2 text-xs leading-5 font-semibold bg-green-100 text-green-800&quot;]</value>
      <webElementGuid>7b17f9ee-e110-42b3-bdec-19ca9a96b939</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/main/div/div[2]/div[2]/div[2]/div/table/tbody/tr/td[3]/span</value>
      <webElementGuid>fd1fe3a4-f991-4a6d-9ab6-1d4ba82df87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[5]/following::span[1]</value>
      <webElementGuid>d46a73d6-321f-4c35-a8e0-69b880246032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='john.doe2@example.com'])[2]/following::span[2]</value>
      <webElementGuid>b02694e6-7b48-48ec-927b-eb75d8063d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sep 17, 2025'])[3]/preceding::span[1]</value>
      <webElementGuid>c1b919b6-09e4-4fc2-ae26-b2d936a71df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group 21'])[2]/preceding::span[2]</value>
      <webElementGuid>63258240-b0f8-4baa-a7a4-da408233ae6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>ace92206-bcc2-42ed-87ce-919e48e6069f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>20f2bec1-93ba-472c-830f-0b2584123ea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
