<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Actions_text-sm font-medium text-gray-900</name>
   <tag></tag>
   <elementGuidId>37ea62d6-90be-4b04-9e55-2e42c5ef42c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-sm.font-medium.text-gray-900</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/main/div/div[2]/div[2]/div[2]/div/table/tbody/tr/td/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=table >> internal:text=&quot;Minh&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d0c175b-5934-4334-afe7-84dd9916e983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-medium text-gray-900</value>
      <webElementGuid>e27ae393-2d8d-4cba-b683-b3b5669b335c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Minh</value>
      <webElementGuid>06791ca9-bd21-41b6-839a-6b86da6478f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/main[@class=&quot;h-[calc(100vh-4rem)] overflow-y-auto bg-gray-50 pb-20&quot;]/div[@class=&quot;container mx-auto px-4 py-6 sm:py-8&quot;]/div[@class=&quot;mb-6&quot;]/div[@class=&quot;hidden md:block&quot;]/div[@class=&quot;rounded-md border&quot;]/div[@class=&quot;relative w-full overflow-x-auto&quot;]/table[@class=&quot;w-full caption-bottom text-sm&quot;]/tbody[@class=&quot;[&amp;_tr:last-child]:border-0&quot;]/tr[@class=&quot;data-[state=selected]:bg-muted border-b transition-colors hover:bg-gray-50&quot;]/td[@class=&quot;p-2 align-middle whitespace-nowrap [&amp;:has([role=checkbox])]:pr-0 [&amp;>[role=checkbox]]:translate-y-[2px] py-4&quot;]/div[@class=&quot;flex items-center&quot;]/div[@class=&quot;ml-4&quot;]/div[@class=&quot;text-sm font-medium text-gray-900&quot;]</value>
      <webElementGuid>e6d708a6-038e-4e1b-b197-f6d8b5256540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/main/div/div[2]/div[2]/div[2]/div/table/tbody/tr/td/div/div[2]/div</value>
      <webElementGuid>059aa742-eb19-4b61-8473-9f56b442fe34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::div[4]</value>
      <webElementGuid>6d6bccdc-4618-4964-a8b5-162db93e878a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/following::div[4]</value>
      <webElementGuid>ff4ed525-a829-407b-a559-5d1a9f7ee7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='minhcaoduy@gmail.com'])[2]/preceding::div[1]</value>
      <webElementGuid>b342e281-d536-493b-8e31-9e7d14c7a62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin'])[6]/preceding::div[2]</value>
      <webElementGuid>826739b6-6f4c-4086-b624-8a0b5be13f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div</value>
      <webElementGuid>221e84cb-6d4c-42f7-88b2-42e664e5494a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Minh' or . = 'Minh')]</value>
      <webElementGuid>d282eb81-5301-482f-b750-0893fdbf24a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
